LPS-92609 Get frontend-js-web tests passing again
Updating the Babel dependencies solves these errors which were causing
every single test to fail:

    TypeError: Cannot read property 'bindings' of null

but note that I had to change one `import` in tests because we were
importing un-transpiled ES6 and that was leading to errors like this:

    modules/node_modules/metal-events/src/EventEmitter.js:3
    import { array, Disposable, isFunction, isString } from 'metal';
           ^

    SyntaxError: Unexpected token {