LPS-92609 Fix dynamic-data-mapping-form-builder Jest tests
Note that in addition to replacing and reconfiguring a bunch of
dependencies I also had to fix a mock return value that was causing
errors like these to blow up:

    ● LayoutProvider/handlers/fieldDeletedHandler ›
    handleFieldDeleted(state, event) › should call removeRow() when
    row is left with no fields after delete operation

      TypeError: Invalid attempt to spread non-iterable instance