LPS-200720 This css doesn't exist and it is causing poshi failures:
LIFERAY_ERROR: Skip com_liferay_site_navigation_admin_web_portlet_SiteNavigationAdminPortlet:/o/site-navigation-admin-web/css/main.css because its content type is not CSS or JavaScript