LPS-92609 Fix binding errors in dynamic-data-mapping-form-web tests
All the tests were blowing up with:

    ● Test suite failed to run

      TypeError: Cannot read property 'bindings' of null

due to this reference to an older version of a babel package.