LPS-148445 Fix GoogleJavaScriptMinifier log errors
Even though the whole JavaScriptMinifier feature is deprecated, we were getting
errors when the CI tests were run because it seems to be turned on in that case
(see https://liferay.slack.com/archives/C3JBR21HA/p1648799114449479).

For the record, the errors looked like:

LIFERAY_ERROR: (/o/js/resolved-module/@frontend-taglib-clay$clayui/drop-down@3.49.0/index.js:1): Failed to load module "../../../../frontend-taglib-clay/__liferay__/exports/@clayui$drop-down.js" [JSC_JS_MODULE_LOAD_WARNING]

These errors are caused by the appearance of "import from" declarations in our
ESM .js files (we use that in the ESM to AMD bridges and in all other ESM files).

In the case of ESM to AMD bridges, the ComboServlet may serve them (as they are
fetched by the AMD loader from the server), so they could eventually be parsed by
the JavaScriptMinifier, making it fail.

What I'm doing in this commit is to prevent the minifier from being invoked for
those new ESM to AMD bridges. The rationale is that the minifier is already
deprecated, so we shouldn't apply it to new artifacts, nor modify it to make it
work for them. We can simply stop invoking it and everything should be fine.

Additionally, the ESM to AMD bridges are a temporary thing that we will remove
when everything has been migrated to ESM, so there's no point in making the
minifier work for them.