LPD-30302 gradle-plugins-workspace: test: fixes classpath issue
Failing tests:
targetPlatformCustomDistro
targetPlatformDefault
targetPlatformVersion

Error:

Caused by: java.lang.NoSuchMethodError: org.osgi.service.resolver.ResolveContext.onCancel(Ljava/lang/Runnable;)V
	at org.apache.felix.resolver.ResolverImpl$ResolveSession.createSession(ResolverImpl.java:100)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:420)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at biz.aQute.resolve.BndResolver.resolve(BndResolver.java:32)