LPD-15685 import commons-math3 from shared-dependencies-apache-commons to shared-dependencies-poi, so that we can avoid "NoClassDefFoundError: org/apache/commons/math3/.."