LPS-129051 Remove unneeded propsTransformer attribute
In [`22b0aff`](https://github.com/liferay/liferay-portal/commit/22b0aff696eff783ec4016c7942a3da853d9de16),
we migrated `<clay:management-toolbar-v2 />` to
`<clay:management-toolbar />`, and introduced a bug:

The instances of the `<clay:management-toolbar />` tag in
[select_organization_role.jspf](https://github.com/liferay/liferay-portal/blob/aa7b7141b63ef4781020c31783b3cdd13fc883f0/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/select_organization_role.jspf) and
[select_site_role.jspf](https://github.com/liferay/liferay-portal/blob/aa7b7141b63ef4781020c31783b3cdd13fc883f0/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/select_site_role.jspf)
don't need a `propsTransformer` attribute and adding it will show the
following JavaScript error in the brower's console when these JSPs are loaded

```
TypeError: Cannot read property 'deleteRolesURL' of undefined
    at Object.propsTransformer [as default] (ViewRolesManagementToolbarPropsTransformer.js:18)
```

This change fixes the JavaScript error.

However, even when reverting [these changes](https://github.com/liferay/liferay-portal/commit/22b0aff696eff783ec4016c7942a3da853d9de16), the search results
are still not shown correctly.