LPD-82456 Service builder/Source Fomatter/RestBuilder build.gradle has this unusual kernel version locking 	constraints { 		compileOnly(group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "154.0.0") { 			because "Java 8 runtime support is required" 		} 	}
This causes 	@com.liferay.portal.kernel-*.jar!/com/liferay/portal/kernel/util/*,\

is including SystemProperties from that specific release, which still has dependency to kernel UnsyncByteArrayInputStream.

Add back the kernel classes including to avoid the following error.

     [java] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/portal/kernel/io/unsync/UnsyncByteArrayInputStream
     [java] 	at com.liferay.portal.kernel.util.SystemProperties.load(SystemProperties.java:190)
     [java] 	at com.liferay.portal.kernel.util.SystemProperties.<clinit>(SystemProperties.java:304)
     [java] 	at com.liferay.portal.kernel.log.SanitizerLogWrapper.<clinit>(SanitizerLogWrapper.java:293)
     [java] 	at com.liferay.portal.kernel.log.LogFactoryUtil.getLog(LogFactoryUtil.java:35)
     [java] 	at com.liferay.portal.kernel.log.LogFactoryUtil.getLog(LogFactoryUtil.java:20)