LPS-53392 Update the bnd of portal-tools-upgrade-table-builder to fix classpath errors when running the task otherwise we get errors like this:
Buildfile: /home/dev/git/liferay/ce/liferay-portal/portal-impl/build.xml

build-upgrade-table:

prepare-upgrade-table:
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: com/liferay/portal/kernel/util/StringBundler
     [java]     at com.liferay.portal.kernel.util.Validator.<clinit>(Validator.java:1358)
     [java]     at com.liferay.portal.tools.ArgumentsMap.get(ArgumentsMap.java:30)
     [java]     at com.liferay.portal.tools.ArgumentsMap.get(ArgumentsMap.java:24)
     [java]     at com.liferay.portal.tools.upgrade.table.builder.UpgradeTableBuilder.main(UpgradeTableBuilder.java:53)
     [java] Caused by: java.lang.ClassNotFoundException: com.liferay.portal.kernel.util.StringBundler
     [java]     at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [java]     at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]     ... 4 more
     [java] Java Result: 1

BUILD SUCCESSFUL
Total time: 1 second