LPD-97689 Export com.microsoft.schemas.vml from poi-ooxml-lite dependency
This is to resolve `NoClassDefFoundError` when processing OOXML Word documents. Tika 3.x's OOXML Word extractor now requires `com.microsoft.schemas.vml.impl.CTShapeImpl` whenever a document contains an embedded object.