LPS-96376 Back out changes to and exclude modules/test/poshi-runner
Bot won't allow changes to this directory:

    error: Illegal change to a pull-only subdir modules/test/poshi-runner.