LPS-129853 Tweak types in remote-app-client-js
4 new errors caused by increased strictness in the newer version of
TypeScript:

    https://gist.github.com/wincent/706405b00ce15113ed0fc2657a8db378

All of the form:

    src/main/resources/META-INF/resources/js/index.ts:598:10 - error TS2322: Type '(value: Blob | PromiseLike<Blob>) => void' is not assignable to type '(value?: Blob | undefined) => void'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'Blob | undefined' is not assignable to type 'Blob | PromiseLike<Blob>'.
          Type 'undefined' is not assignable to type 'Blob | PromiseLike<Blob>'.

Test plan: `yarn run build` in `remote-app-client-js`