LPS-92609 Attempt fix for dynamic-data-mapping-form-web tests
This applies a similar update to the ones I made in previous commits,
but alas, I'm still getting the error:

    TypeError: Cannot read property 'bindings' of null

which I would have expected the Babel dependency updates to address.
I'll continue investigating this tomorrow.